package com.mindhub.salvo;

import org.hibernate.annotations.GenericGenerator;
import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.*;

@Entity
public class GamePlayer {

    @Id // every @Entity/object from the class GamePlayer which is an arrow --->
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "native") // will be identified by a unique ID
    @GenericGenerator(name = "native", strategy = "native") // generated by Spring
    private long id;

    private LocalDateTime date;

    @ManyToOne(fetch = FetchType.EAGER) // relation of Many(GamePlayer) to Many(Player)
    @JoinColumn(name = "player_id")
    // Player is identified by a unique player ID in a column in the GamePlayerRepository
    private Player player;                      // GamePlayer class will be receiving two objects: Player and Game

    @ManyToOne(fetch = FetchType.EAGER) // relation of Many(GamePlayer) to Many(Game)
    @JoinColumn(name = "game_id") // Game is identified by a unique game ID in a column in the GamePlayerRepository
    private Game game;

    @OneToMany(mappedBy = "gamePlayer", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    // relation que hay con Ship a través de la propiedad "gamePlayer"
    private Set<Ship> ships = new HashSet<>();

    @OneToMany(mappedBy = "gamePlayer", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    // relation que hay con Salvo a través de la propiedad "gamePlayer"
    private Set<Salvo> salvos = new HashSet<>();

    public GamePlayer() {
    } // empty constructor

    public GamePlayer(Player player, Game game, LocalDateTime date) {
        this.player = player;    // Non-empty constructor which will be receiving when the GamePlayer object is created
        this.game = game;          // a Player, a Game, a Date, a Ship and a score
        this.date = date;
    }

    public Score getScore() {
        return player.getScore(game);
    }

    public void setId(long id) {
        this.id = id;
    }

    public Set<Ship> getShips() {
        return ships;
    }

    public Set<Salvo> getSalvos() {
        return salvos;
    }

    public long getId() { // An ID is received

        return id;
    }

    public Player getPlayer() { // A Player is received

        return player;
    }

    public void setPlayer(Player player) { // A Player is modified

        this.player = player;
    }

    public Game getGame() {  // A Game is received

        return game;
    }

    public void setGame(Game game) { // A Game is modified

        this.game = game;
    }

    public LocalDateTime getDate() { // A Date is received

        return date;
    }

    public void setDate(LocalDateTime date) { // A Date is modified

        this.date = date;
    }

    public void addShip(Ship ship) {
        ship.setGamePlayer(this);
        ships.add(ship);
    }

    public void addSalvo(Salvo salvo) {
        salvo.setGamePlayer(this);
        salvos.add(salvo);
    }

    public Optional<GamePlayer> getEnemy() {
        return this.game.getGamePlayers().stream().filter(gp -> gp.getId() != this.id).findFirst();
        // returns the gamePlayer which is different from the gamePlayer viewer
    }


    public String gameStateManagement() {

        //A player can't fire a salvo after the game has ended
        // A tie is possible if both players sink each others ships in the same round.
        // When the game ends, the controller should update the game score database
        // 1 point for a win, half a point for a tie, 0 for losing

        Optional<GamePlayer> enemy = this.getEnemy();
        if (this.getShips().isEmpty() && enemy.isPresent()) { // if viewer hasn't placed any ship and enemy exists
            return "Place Ships";
        } else if (enemy.isEmpty()) { // if enemy doesn't exists yet
            return "Wait for your enemy";
        } else {  // salvos porque se quiere recorrer el arreglo de salvos, y getSalvos() porque se quiere obtener el size directamente
            int turnViewer = 0;
            int sunksViewer = 0;
            int turnEnemy = 0;
            int sunksEnemy = 0;
            Optional<Salvo> gpTurn = this.salvos.stream().filter(salvo -> salvo.getTurn() == this.getSalvos().size()).findFirst(); // last turn played
            Optional<Salvo> enemyTurn = enemy.get().salvos.stream().filter(salvo -> salvo.getTurn() == enemy.get().getSalvos().size()).findFirst();

            if (gpTurn.isPresent()) { // vieweeerrr
                turnViewer = gpTurn.get().getTurn(); // gets last turn played by the viewer
                sunksViewer = gpTurn.get().getSunkenShips().size(); // gets sunken ships from the last turn
            } else if (enemyTurn.isPresent()) {
                turnEnemy = enemyTurn.get().getTurn(); // gets last turn played by the enemy
                sunksEnemy = enemyTurn.get().getSunkenShips().size(); // gets sunken ships from the last turn
            }

            if(this.getShips().size() == 5 && enemy.get().getShips().size() != 5){
                return "Wait for your opponent";
            }else if (this.getShips().size() == 5 && enemy.get().getShips().size() == 5){
                return "You can fire";
            }

            if (turnViewer < turnEnemy) {
                return "You can fire";
            } else if (turnViewer > turnEnemy) {
                return "You must wait";
            } else {
                if (sunksViewer < 5 && sunksEnemy == 5) {
                    return "You lost";
                } else if (sunksViewer == 5 && sunksEnemy < 5) {
                    return "You won";
                } else if (sunksViewer == 5 && sunksEnemy == 5) {
                    return "Tie";
                }
            }
        }
    }
}
